// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("Masterframeindex.html", "Monastero di Santa Chiara di Acquapendente", "monastero di santa chiara acquapendente emergenza nbsp terremoto comunicati documentazione donazioni dove siamo contatti home storia comunit monastica attivit del vocazioni spiritualit clariano mariana punti fondamentali fotografie via malintoppa vt info monasterodiacquapendente it ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Masterframeindex.html", "Monastero di Santa Chiara di Acquapendente", "monastero di santa chiara acquapendente the nbsp earthquake emergency press communiqu documentation donations where we are contact information home history monastic community work vocations spirituality clarian marian fundamental points photographs via malintoppa vt info monasterodiacquapendente it ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("Masterframe.html", "Monastero di Santa Chiara di Acquapendente", "monastero di santa chiara acquapendente emergenza nbsp terremoto comunicati documentazione donazioni dove siamo contatti home storia comunit monastica attivit del vocazioni spiritualit clariano mariana punti fondamentali fotografie via malintoppa vt info monasterodiacquapendente it ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Masterframe.html", "Monastero di Santa Chiara di Acquapendente", "monastero di santa chiara acquapendente the nbsp earthquake emergency press communiqu documentation donations where we are contact information home history monastic community work vocations spirituality clarian marian fundamental points photographs via malintoppa vt info monasterodiacquapendente it ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("index.html", "Home | Monastero di Acquapendente", "home monastero di acquapendente nbsp nel nostro sito oltre alle informazioni carattere generale potete trovare notizie relative al terremoto del che ha provocato diverse lesioni danni in alcune zone partecipare alla raccolta fondi avviata per il ripristino dell’area danneggiata inoltre nella sezione documentazione ora disponibile progetto preliminare dei lavori necessari redatto dallo studio architetto fiducia dio vi benedica immacolata ricompensi ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_index.html", "Home | Monastery of Acquapendente", "home monastery of acquapendente nbsp in our site besides other information general nature you can find news about the earthquake which has caused various lesions and damanges some parts may also contribute to fundraising so that we could commence works are necessary recuperate damaged areas moreover section documentation there is available preliminary project for prepared by studio architect trust lord bless blessed virgin mary immaculate reward your kindness ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("CONSTRUCTION_WORKS.html", "Untitled Page", "untitled page nbsp contatti dove siamo monastero di santa chiara via malintoppa acquapendente vt info monasterodiacquapendente it ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_CONSTRUCTION_WORKS.html", "Monastero di Santa Chiara di Acquapendente", "monastero di santa chiara acquapendente nbsp contact information where we are via malintoppa vt info monasterodiacquapendente it ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("Storia.html", "Storia | Monastero di Acquapendente", "storia monastero di acquapendente frati minori erano già presenti ad vivente il serafico padre san francesco che al suo passaggio in questa zona vi lasciò suoi confratelli un povero conventino presso fiume paglia nell’anno fu loro concessa la chiesa detta maria del borgo cui seguito aggiunto titolo tuttora esistente fin dagli inizi tossignano altri storici nel convento annesso alla fiorirono religiosi insigni maestri eloquenza tra essi spicca tommaso da ministro provinciale della provincia romana penitenziere apostolico sotto pontificato giovanni xxii presenza dei terziari appare anche subito fianco con contributo popolazione costruì santa chiara tale ricordato quali blaeu ed de rossi per costruzione scelto colle poco sopra porta fiorentina detto “la cittadella” “il poggio massaro” dove passato sorgeva l’antica fortezza l’atto concessione alle monache datato giugno sottoscritto teodoro cardinale legato prima comunità clarisse formata provenienti dai monasteri orvieto bagnoregio si aggiunsero le aspiranti luogo breve dicembre pio iv mise l’autorità tutela sforza camerlengo napoleone bonaparte mandò via usurpando chiesetta razziando devastando beni pala d’altare sottratta quell’epoca l’archivio bruciato fecero ufficialmente ritorno ma realtà sa esse non lo abbandonarono mai riuscendo vivere come secolari all’interno delle sacre mura può quindi ragion veduta parlare ininterrotta ormai quasi secoli l’attuale monastica dopo oltre anni aridità trova all’inizio una rifioritura vocazioni negli ultimi benedizione dio sguardo materno dell’immacolata ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_History.html", "History | Monastery of Acquapendente", "history monastery of acquapendente our town already boasted the presence friars minor during lifetime seraphic father st francis who passing through area asked some his brethren to remain here in poor little friary near river paglia church known as santa maria del borgo was granted them which later received additional name still exists this day from very beginning according testimony tossignano and other historians attached home noteworthy religious remarkable for their eloquence nbsp outstanding amongst fr thomas minister provincial roman province well apostolic penitentiary pontificate pope john xxii alongside there were franciscan tertiaries first years it that particular aided by people built saint clare is mentioned such blaeu de rossi place chosen where build hill above florentine gate “the citadel” or “massaro’s knoll times past ancient fortress had stood deed nuns bears date june signed theodore cardinal legate founding community clares composed monasteries orvieto bagnoregio hometown bonaventure great general considered second founder order aspirants itself its environs with brief bearing december pius iv placed beneath authority protection sforza camerlengo holy napoleon bonaparte drove away usurping laying waste patrimony plundering altarpiece stolen period community’s archives burned on paper returned but truth they not abandoned at all living meantime within walls secular dress we can thus truly say boasts an uninterrupted dating back nearly seven hundred god’s grace after more than forty aridity present monastic new flowering vocations these last under motherly immaculate echoing days clare’s reached france spain bohemia chooses her daughters only italy world fact throughout number saints have left homeland follow christ veronica giuliani bl florida cevoli mary crucifixa own city states enter others margaret sinclair scotland england sr trinity switzerland jerusalem ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("Comunita_Monastica.html", "Comunità Monastica | Monastero di Acquapendente", "comunità monastica monastero di acquapendente comunit la nostra famiglia clarisse dell’immacolata come nuovo ramo dell’ordine santa chiara d’assisi dedita vita integralmente contemplativa professa l’osservanza del vangelo secondo regola confermata da innocenzo iv le costituzioni proprie che prevedono anche il voto consacrazione all’immacolata non facciamo parte nessun istituto religiosa ma unicamente siamo spiritualmente unite al primo ordine san francesco tutti monasteri nostro fraternamente in comunione con l’ordine francescano secolare modo particolare fraternità assisi unita un gemellaggio spirituale nbsp clicca sull icona per video ricordo ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Monastic_Community.html", "Monastic Community | Monastery of Acquapendente", "monastic community monastery of acquapendente our family poor clares the immaculate is new branch order st clare assisi wholly contemplative we profess observance holy gospel according to rule confirmed by innocent iv along with own particular constitutions which call for vow consecration do not belong any institute or religious but exclusively are united spiritually first francis and all monasteries furthermore share fraternal communion secular franciscan in special way franciscans spiritual “twinning” nbsp click on icon watch visual memento ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("Attivita_del_Monastero.html", "Attività | Monastero di Acquapendente", "attività monastero di acquapendente attivit del seguendo gli insegnamenti nostro serafico padre san francesco viviamo in povertà individuale comunitaria affidandoci alla divina provvidenza il poverissimo anche seguito alle soppressioni napoleoniche che espropriarono le monache arredi liturgici ed altri beni la comunità vive proprio lavoro delle libere offerte donazioni riceviamo secondo tradizione si confezionano paramenti sacri semplici oppure ricamati mano rimettono posto quelli vecchi al rivolgono numerosissime parrocchie santuari lazio della toscana particolare oltre sacerdoti secolari da tutta italia alcune roma ricorrono per lo stiro biancheria chiesa chiediamo ai un’offerta questo modo intendiamo riattualizzare continuare l’opera madre santa chiara con sue mani filava tesseva lini preziosi chiese più povere bisognose confezioni ricami prettamente ecclesiastici rispondono numerose richieste provengono famiglie singoli corredi cuscinetti spose riparazioni inamidatura centrini merletti all’arte rammendo vero su abiti giacche pantaloni ecc come secondaria provvedono produzione statuine presepi gesso dipinti ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Monastic_Work.html", "Monastic Work | Monastery of Acquapendente", "monastic work monastery of acquapendente we follow the teachings our seraphic father st francis living in poverty both individual and collective entrusting ourselves to divine providence is extremely poor by free choice as result napoleonic period when liturgical furnishings much else monastery’s patrimony was destroyed or stolen live hands spontaneous offerings money goods from benefactors according traditions hand sew prepare sacred vestments embroidered simple restore antique for good number parishes sanctuaries especially regions lazio tuscany well diocesan priests all over italy some rome have entrusted nuns with washing ironing upkeep their altar linens ask donation exchange are blessed this carry on same done holy mother clare who her own used spin weave precious poorest churches besides sewing embroidery church fulfill requests works families individuals household wedding ring cushions mending starching lace doilies shawls other articles type art properly speaking dresses jackets trousers etc an additional activity produce statuettes nativity scenes out plaster paris ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("Vocazioni.html", "Vocazioni | Monastero di Acquapendente", "vocazioni monastero di acquapendente nella sua realtà più profonda la vocazione religiosa rimane un mistero e’ scelta rischiare vita per dio risposta all’amore nostra come monache integralmente contemplativa agli occhi del mondo uno spreco ma lo “spreco” che maddalena fa ai piedi gesù mentre lui stesso difende “lasciatela fare” dell’amore si dona senza cercare ricompensa se noi molti riesce incomprensibile ragione intima una consacrata interamente ad ideale misterioso quasi sempre perché essi sfugge il fatto questo “ideale” persona chiamata non autonoma incontro personale con signore capace cambiare importante ognuno prima compiere le scelte fondamentali della propria chieda stesse parole san francesco “signore cosa vuoi io faccia?” nel tuo cuore senti ti sta chiamando sceglie sposa affrettati rispondere questa domanda semplicità “eccomi ancora hai cammino discernimento capire generosità condizione necessaria felicità terrena percorrere strada salvezza eterna maggiore facilità trovando lungo tutte grazie spirituali ragazze sentono desiderio vivere claustrale sono invitate contattare poter eventualmente fare vocazionale conoscere meglio spiritualità clarissa dell immacolata comunità monastica prega continuamente coloro chiama possano gioia coraggio incessante preghiera ritmata silenzio nascondimento battito nutre forma dialogo vitale amore divino scambia tra cristo impegno bene sperimentiamo privilegio donatoci dal confermato dalla santa chiesa ci permette dedicarci intera essere testimoni strumenti efficaci voluta da tutto ottenuta attraverso infinite sulla croce ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Vocations.html", "Vocations | Monastery of Acquapendente", "vocations monastery of acquapendente deep down religious vocation is always mystery it the choice to risk one’s life for god answer love eyes world wholly contemplative wasted in truth as wasteful perfumed ointment that mary magdalene poured out on christ’s feet while he himself came her defense “let do” “waste” gives its whole self without seeking anything return jesus gave up us many are unable grasp sense such ours which seems entirely given over some mysterious ideal almost because they unaware this “ideal” person every an voice calling never one sided decision personal meeting with lord capable changing each before choosing our path must ask very words st francis “lord what would you have me do?” if hear his call your heart and feel become bride make sure give humble simplicity “here am other hand not yet taken step considering wants from don’t waste time learning carrying generosity “conditio sine qua non” be happy here earth proceed more easily through eternal salvation abundantly full graces by along way we invite young ladies who wish understand whether them cloistered contact order explore possibility learn about spirituality poor clares immaculate lived monastic community prays continually those whom calls enclosure may respond joy courage unceasing prayer following rhythm silence like beat nbsp nourished vital dialogue divine exchanged between christ spouse experience commitment live privilege confirmed holy mother church allows dedicate entire witnesses efficient instruments wanted obtained infinite cross ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("Spiritualita.html", "Spiritualità | Monastero di Acquapendente", "spiritualità monastero di acquapendente spiritualit clariano mariana punti fondamentali ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Spirituality.html", "Spirituality | Monastery of Acquapendente", "spirituality monastery of acquapendente clarian marian fundamental points ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("Spiritualita_Clariano_Mariana.html", "Spiritualità | Monastero di Acquapendente", "spiritualità monastero di acquapendente l’esperienza contemplativa la conformazione al crocifisso povero povertà betlemme rendono nostra fraternità una scelta evangelica autentica che nella clausura papale esprime totalità dell’amore per ripetere della primitiva francescana “conservando l’unità scambievole carità vincolo perfezione” come insegna madre santa chiara nascoste con cristo in dio col nel mistero del “piccolo chiostro santo seno” lett agnese maria viviamo mezzo privilegiato ci permette essere quot cristificate dimensione dell’altissima vita oltre ad arricchirsi alle fonti ispirative dei fondatori nostro ordine san francesco attinge anche il suo carattere mariano negli scritti massimiliano kolbe castità consacrata testimonianza sponsale “povertà l’umiltà signore gesù sua santissima vissuta espropriazione totale l’obbedienza “fino alla morte” chiamata dal serafico padre “sorella carità” si nutre unicamente “unico necessario” tradizione propria dell’ordine assunta forza voto sono punti fondamentali ma modo speciale clarissa dell’immacolata conforma attraverso consacrazione all’immacolata “illimitata incondizionata irrevocabile” nell’impegno apostolico far conoscere amare imitare glorificare l’immacolata preghiera continua l’offerta sé sacrificio lode sacra liturgia cui le sorelle lodano cuore chiesa celebrata ogni giorno lingua latina forma vuole centro culmine tutta silenzio penitenza comunione fraterna suffragio estende vincoli tra morte completano ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Clarian_Marian_Spirituality.html", "Spirituality | Monastery of Acquapendente", "spirituality monastery of acquapendente our community lives the true gospel life marked by contemplation conformity to christ poor and crucified infant in bethlehem nuns means papal enclosure can live love that gives itself fully making present anew church spirit beginnings second franciscan order “keeping unity mutual which is bond perfection as holy mother st clare teaches hidden with god col mystery “little cloister womb” mary rd letter agnes we privileged become more “christlike” part most high poverty draws its strength from founders francis marian character writings maximilian maria kolbe consecrated chastity testimony spousal for “poverty humbleness lord jesus his mother” lived total expropriation obedience “till death” called seraphic father “sister charity” nourished only “the necessary” according tradition contracted force vow are fundamental points thus special way each immaculate conforms herself an “unlimited unconditional irrevocable” consecration apostolic work make known loved imitated glorified unceasing prayer offering ourselves sacrifice praise sacred liturgy sisters heart voice takes place every day latin form handed down it truly source summit all silence penance fraternal communion lasts beyond grave prayers who have gone before us up rest ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("Spiritualita_Punti_fondamentali.html", "Spiritualità | Monastero di Acquapendente", "spiritualità monastero di acquapendente nbsp la castità consacrata testimonianza dell amore sponsale per cristo povertà umiltà del signore gesù della sua santissima madre vissuta come espropriazione totale obbedienza quot fino alla morte chiamata dal serafico padre sorella carità clausura papale vita che si nutre unicamente dio unico necessario tradizione propria ordine assunta con forza voto clarissa immacolata conforma attraverso consacrazione all illimitata incondizionata irrevocabile nell impegno apostolico far conoscere amare imitare glorificare preghiera continua offerta sé il sacrificio lode comunione fraterna estende vincoli tra le sorelle anche oltre preghiere suffragio sacra liturgia cui lodano nel cuore chiesa celebrata ogni giorno in lingua latina nella forma nostro centro culmine tutta fraternità silenzio penitenza completano nostra ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Fundamental_Points_Our_Spirituality.html", "Spirituality | Monastery of Acquapendente", "spirituality monastery of acquapendente nbsp consecrated chastity testimony spousal love for christ the poverty and humbleness lord jesus his most holy mother lived as total expropriation obedience quot till death called by seraphic father sister charity papal enclosure life nourished only god necessary according to tradition order is contracted force vow poor clare immaculate conforms herself means an unlimited unconditional irrevocable st maximilian kolbe consecreation in apostolic work make known loved imitated glorified unceasing prayer offering oneself sacrifice praise fraternal communion which lasts beyond grave with our prayers nuns who have gone before us sacred liturgy sisters heart voice church celebrated every day latin form handed down source summit all community silence penance complete rest ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("Fotografie.html", "Fotografie | Monastero di Acquapendente", "fotografie monastero di acquapendente ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Photographs.html", "Photographs | Monastery of Acquapendente", "photographs monastery of acquapendente ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("Emergenza_Terremoto.html", "Emergenza Terremoto | Monastero di Acquapendente", "emergenza terremoto monastero di acquapendente comunicati documentazione ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Earthquake_Emergency.html", "Earthquake Emergency | Monastery of Acquapendente", "earthquake emergency monastery of acquapendente press communiqu documentation ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("Comunicati.html", "Comunicati - Emergenza Terremoto| Monastero di Acquapendente", "comunicati emergenza terremoto monastero di acquapendente comunicato urgente ottobre dio vi benedica l’immacolata ricompensi aggiornamento del dicembre versione inglese sito marzo monasterocari amici lingua da oggi il nostro disponibile anche in attraverso questo ulteriore canale informazione desideriamo che sia conosciuto all’estero testimonianza della nostra forma vita clariano mariana inoltre far presente tutti voi la situazione attuale dopo maggio nella zona tuscia quelli successivi agosto hanno lasciato vari danni nel stabile rendendo inagibile chiesa coro monastico parte dormitorio confidiamo come già fanno tanti benefattori italia sostegno morale spirituale finanziario vorrete dare alla comunità monastica dal passato varie vicende non mai mancata protezione divina provvidenza su luogo sacro invitiamo partecipare ognuno secondo le proprie possibilità allo sforzo ogni giorno monache compiono per mantenere viva salda questa opera benedetto signore prescelto dall’immacolata stabilirvi suo “roseto” serafico padre san francesco beata madre chiara accompagnino lungo cammino vostra santissima vergine immacolata custodisca interceda presso trono generosità abbadessa nbsp bull urgent communiqué ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Communiques.html", "Communiqués - Earthquake Emergency | Monastery of Acquapendente", "communiqués earthquake emergency monastery of acquapendente urgent communiqu october update december updatedear friends the we wish to thank you all for many initiatives organized in our aid various offerings small and big that have donated bear your hearts us future thanks felt surrounded as always by affection esteem because service prayer offer may lord bless ask remain contact with through website www monasterodiacquapendente it where periodically follow fundraising being carried out from will also about situation meanwhile are still an initial phase means necessary inspections plans preliminary project shall be made order understand magnitude expense immaculate help saint francis who never fails show his signs extraordinary protection intervene support holy christmas while remember dear families at feet baby jesus mother abbess monastic community communiquéon aftermath struck zone called “tuscia” after repeated seismic shocks continued latium months followed church apse choir enclosure part dormitory been seriously damaged provide securing these premises redoing roofing consolidation vault raising up funds amount need start works on is impossible reach own meager but rely generosity those know others notwithstanding their not familiar would unite themselves pray every day presenting intentions benefactors even offering mass once month possible email specify particular recommend god reward kindness bull march nbsp english version communiqué ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("Documentazione.html", "Documentazione - Emergenza Terremoto  | Monastero di Acquapendente", "documentazione emergenza terremoto monastero di acquapendente ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Documentation.html", "Documentation - Earthquake Emergency | Monastery of Acquapendente", "documentation earthquake emergency monastery of acquapendente ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("PROGETTO PRELIMINARE.pdf.html", "Untitled Page", "untitled page ", "");
   this[database_length++] = new SearchPage("EN_PROGETTO PRELIMINARE.pdf.html", "Untitled Page", "untitled page ", "");
   this[database_length++] = new SearchPage("EN_PROGETTO PRELIMINARE (v1.35).pdf.html", "Untitled Page", "untitled page ", "");
   this[database_length++] = new SearchPage("PROGETTO PRELIMINARE (v1.35).pdf.html", "Untitled Page", "untitled page ", "");
   this[database_length++] = new SearchPage("Coro Claustrale COMPUTO.pdf.html", "Untitled Page", "untitled page ", "");
   this[database_length++] = new SearchPage("Noviziato Parlatorio COMPUTO.pdf.html", "Untitled Page", "untitled page ", "");
   this[database_length++] = new SearchPage("Donazioni.html", "Donazioni | Monastero di Acquapendente", "donazioni monastero di acquapendente attraverso un versamento sul conto corrente postale con bonifico bancario iban it bic swift bppiitrrxxx carta credito utilizzando il bottone paypal la piattaforma buonacausa org se vuoi aiutare nostra comunità monastica puoi farlo una donazione ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Donations.html", "Donations | Monastery of Acquapendente", "donations monastery of acquapendente through deposit to our post office account only for italy bank transfer iban it bic swift bppiitrrxxx with credit card using paypal click on “buonacausa” if you would like help monastic community may do so donation ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("DoveSiamo.html", "Dove siamo | Monastero di Acquapendente", "dove siamo monastero di acquapendente santa chiaravia malintoppa vt ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Where_we_are.html", "Where we are | Monastery of Acquapendente", "where we are monastery of acquapendente monastero di santa chiaravia malintoppa vt the st clare chiara is located in province viterbo italy region lazio near borders tuscany and umbria less than two hours north rome nearest train station orvieto there also daily coach bus between ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("Contatti.html", "Contatti | Monastero di Acquapendente", "contatti monastero di acquapendente per contattarci scrivi oppure chiama nbsp segreteria telefonica info monasterodiacquapendente it ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("EN_Contact_Information.html", "Contact Information | Monastery of Acquapendente", "contact information monastery of acquapendente to us write or call nbsp answering machine info monasterodiacquapendente it ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("errors/401/index.html", "Monastero di Santa Chiara di Acquapendente", "monastero di santa chiara acquapendente emergenza nbsp terremoto comunicati documentazione donazioni dove siamo contatti home storia comunit monastica attivit del vocazioni spiritualit clariano mariana punti fondamentali fotografie via malintoppa vt info monasterodiacquapendente it errore accesso non autorizzato ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("errors/403/index.html", "Monastero di Santa Chiara di Acquapendente", "monastero di santa chiara acquapendente emergenza nbsp terremoto comunicati documentazione donazioni dove siamo contatti home storia comunit monastica attivit del vocazioni spiritualit clariano mariana punti fondamentali fotografie via malintoppa vt info monasterodiacquapendente it errore accesso proibito ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("errors/404/index.html", "Monastero di Santa Chiara di Acquapendente", "monastero di santa chiara acquapendente emergenza nbsp terremoto comunicati documentazione donazioni dove siamo contatti home storia comunit monastica attivit del vocazioni spiritualit clariano mariana punti fondamentali fotografie via malintoppa vt info monasterodiacquapendente it errore link non trovato ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   this[database_length++] = new SearchPage("errors/500/index.html", "Monastero di Santa Chiara di Acquapendente", "monastero di santa chiara acquapendente emergenza nbsp terremoto comunicati documentazione donazioni dove siamo contatti home storia comunit monastica attivit del vocazioni spiritualit clariano mariana punti fondamentali fotografie via malintoppa vt info monasterodiacquapendente it errore interno al server ", "Monastero di Santa Chiara di Acquapendente   fondato nel 1333 ");
   return this;
}
